# Generated by Django 5.0.6 on 2024-08-16 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan_app', '0003_hotels_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homestays',
            name='user',
        ),
        migrations.RemoveField(
            model_name='hotels',
            name='user',
        ),
    ]
