# Generated by Django 5.0.6 on 2024-08-20 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan_app', '0004_remove_homestays_user_remove_hotels_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='total_price',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
