# Generated by Django 5.0.6 on 2024-08-20 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan_app', '0005_bookings_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='homestaybooking',
            name='total_price',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
