# Generated by Django 5.0.6 on 2024-08-21 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan_app', '0006_homestaybooking_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
