# Generated by Django 5.0.6 on 2024-08-21 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan_app', '0007_login_is_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='payment_status',
            field=models.CharField(default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='bookings',
            name='stripe_payment_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
